media:
  input: "static/images/uploads"
  output: "/images/uploads"
content:
  - name: posts
    label: Posts
    type: collection
    path: 'content/posts'
    fields:
      - name: title
        label: Title
        type: string
      - name: Publish Date
        label: date
        type: date
      - name: draft
        label: Draft
        type: boolean
        default: false
      - name: body
        label: Body
        type: text
    view:
      fields: [ title ]
      primary: title
      sort: [ date, title ]
      default:
        search: ''
        sort: title
        order: desc
